import type { NewsletterBlock } from './types'

// Brand colors (matching build-block.ts)
const BRAND = {
  sage500: '#5a6b4a',
  sage700: '#3d4a30',
  cream100: '#f5f5f0',
  cream300: '#e5e5e0',
  textDark: '#1a1a1a',
  textMuted: '#6b7280',
  white: '#ffffff',
} as const

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Format a date like "March 12, 2026"
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

/**
 * Wrap newsletter blocks in a complete email HTML document.
 *
 * Produces a table-based layout with inline styles for maximum
 * email client compatibility (including Outlook).
 *
 * Structure:
 *   - Header: "The Intraday" branding + date + ticker badge
 *   - Blocks: each separated by 24px spacers
 *   - Footer: data source disclaimer + link
 */
export function assembleNewsletterHtml(
  ticker: string,
  blocks: NewsletterBlock[],
  date: Date,
): string {
  const formattedDate = formatDate(date)
  const tickerUpper = escapeHtml(ticker.toUpperCase())

  const blockHtml = blocks
    .map(
      (block) => `
    <!-- Block -->
    <tr><td style="padding:0 0 24px 0;">
      ${block.html}
    </td></tr>`,
    )
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>The Intraday — ${tickerUpper} Snapshot</title>
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <![endif]-->
  <style>
    body, table, td { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    img { border: 0; display: block; }
  </style>
</head>
<body style="margin:0;padding:0;background-color:${BRAND.cream100};">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:${BRAND.cream100};">
    <tr>
      <td align="center" style="padding:32px 16px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="664" style="max-width:664px;">

          <!-- Header -->
          <tr><td style="padding:0 0 32px 0;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:664px;margin:0 auto;background-color:${BRAND.white};border-radius:8px;border:1px solid ${BRAND.cream300};">
              <tr><td style="padding:24px 32px;">
                <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%">
                  <tr>
                    <td>
                      <h1 style="margin:0 0 4px 0;font-family:Georgia,'Times New Roman',serif;font-size:28px;font-weight:700;color:${BRAND.sage700};">
                        The Intraday
                      </h1>
                      <p style="margin:0;font-size:13px;color:${BRAND.textMuted};">
                        ${escapeHtml(formattedDate)}
                      </p>
                    </td>
                    <td align="right" valign="middle">
                      <span style="display:inline-block;padding:6px 16px;background-color:${BRAND.sage500};color:${BRAND.white};font-size:14px;font-weight:600;border-radius:4px;letter-spacing:0.5px;">
                        ${tickerUpper} Snapshot
                      </span>
                    </td>
                  </tr>
                </table>
              </td></tr>
            </table>
          </td></tr>

${blockHtml}

          <!-- Footer -->
          <tr><td style="padding:8px 0 0 0;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:664px;margin:0 auto;">
              <tr><td style="padding:16px 32px;text-align:center;">
                <p style="margin:0 0 8px 0;font-size:11px;color:${BRAND.textMuted};line-height:1.5;">
                  Data sourced from SEC filings and Financial Modeling Prep. Charts generated by The Intraday.
                  This newsletter is for informational purposes only and does not constitute investment advice.
                </p>
                <p style="margin:0;font-size:11px;color:${BRAND.textMuted};">
                  <a href="https://theintraday.com" style="color:${BRAND.sage500};text-decoration:underline;">theintraday.com</a>
                </p>
              </td></tr>
            </table>
          </td></tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}
