export const DEFAULT_CHART_RENDER_WIDTH = 1200
export const DEFAULT_CHART_RENDER_HEIGHT = 675
export const DEFAULT_EDITOR_CHART_RENDER_WIDTH = 1200
export const DEFAULT_EDITOR_CHART_RENDER_HEIGHT = 675
